# Generated by Django 4.1.7 on 2023-04-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=999999999, verbose_name='Текст статьи'),
        ),
    ]
