# Generated by Django 4.1.7 on 2023-04-14 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_news_alter_article_slug_alter_article_text_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Информационные старницы', 'verbose_name_plural': 'Информационная старница'},
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новость'},
        ),
    ]
