# Generated by Django 4.1.7 on 2023-04-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_article_slug_alter_article_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='desc',
            field=models.TextField(default=1, verbose_name='Подробности Новости'),
            preserve_default=False,
        ),
    ]
